### ISSUE TITLE
The description of 'volatile-ttl' differs somewhat from the official website.

### ISSUE THREAD

**Issue by ADD-SP** [RedisLabs/redislabs-docs#1056]
**Current behavior** (A short description of what you found)

`volatile-ttl`: Evicts the **shortest time-to-live and least recently used keys** out of all keys with an “expire” field set.

https://docs.redislabs.com/latest/rs/administering/database-operations/eviction-policy/

**Expected behavior** (A short description of what you expected to find)

`volatile-ttl`: evict keys with an expire set, and **try to evict keys with a shorter time to live (TTL) first**, in order to make space for the new data added.

https://redis.io/topics/lru-cache#eviction-policies

**Screenshots** (Paste or drag-and-drop a screenshot)

![0](https://user-images.githubusercontent.com/44437200/95120966-f2769c80-0780-11eb-8d94-470be544b8fc.png)
***
![1](https://user-images.githubusercontent.com/44437200/95120974-f4406000-0780-11eb-9698-ada91191726a.png)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Thanks for pointing this out @ADD-SP .
@AlonMagrafta , can you comment on the discrepancy?

**Comment by AlonMagrafta** [comment]
@bmansheim we need to fix out docs.redislabs.com site, we just remove the "least recently used" part there.
