### ISSUE TITLE
Timeseries data timestamp truncated to seconds in RedisInsight

### ISSUE THREAD

**Issue by laurafernandezdiaz** [RedisLabs/redislabs-docs#1072]
I have been testing Redis Insight 1.7.1 and I noticed timestamps show wrong when viewing data with Redis Timeseries in Redis Insight. 

![image](https://user-images.githubusercontent.com/51406942/96120397-bbc22400-0eee-11eb-9e51-8cb4bb18358a.png)
![image](https://user-images.githubusercontent.com/51406942/96120348-a9e08100-0eee-11eb-8111-7d1fc5df7127.png)

Data at higher resolutions than 1 second are displayed at the same time point.

Are timestamps being truncated? how can we visualize the points to milliseconds?

Thanks in advance

**Comment by bmansheim** [comment]
Hi @laurafernandezdiaz . Thanks for reaching out!
It looks like this is more of a support issue than a documentation issue but maybe @slemeur can respond here.

**Comment by laurafernandezdiaz** [comment]
Thank you very much for answering @bmansheim. Previously in other versions, the values were correct with their timestamp in ms, however, in recent versions, this is not the case. So it is wrong behavior. Maybe @slemeur can help us.

**Comment by slemeur** [comment]
Hi @laurafernandezdiaz . Thanks for reaching out with the issue you have.
We have not updated TimeSeries tool since few releases, but we can confirm there is an issue with the timestamp. We'll be looking at it and providing a fix quickly! 
Thanks again !
