### ISSUE TITLE
RedisGraph deployment through Azure market place 

### ISSUE THREAD

**Issue by sunkararp** [RedisLabs/redislabs-docs#1080]
**Current behavior** (A short description of what you found)
Not able to deploy RedisGraph in Azure using Marketplace

**Expected behavior** (A short description of what you expected to find)
Need documentation how to deploy RedisGraph in Azure using Marketplace; especially using ARM templates.

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Hi @sunkararp . Thanks for that feedback.
@K-Jo Can you comment?

**Comment by K-Jo** [comment]
@bmansheim @sunkararp We currently don't support RedisGraph in Azure market place.  If this would be a requirement, please reach out to support at redislabs dot com
