### ISSUE TITLE
Replace master by primary in RedisInsight

### ISSUE THREAD

**Issue by raphaelauv** [RedisLabs/redislabs-docs#1117]
**Current behavior** (A short description of what you found)
The current (1.8) RedisInsight for a redis cluster show the word master and not primary ( for a node of the cluster )

**Expected behavior** (A short description of what you expected to find)
Something else than MASTER

Thank you

**Comment by bmansheim** [comment]
Hi @raphaelauv . Thanks for your feedback. We understand the difficulty with the language there and that there is a move in the industry away from master-slave terminology. This is a major process for us that entails changes deep in our code. The change is in our roadmap. Let me know if you need more details.
