### ISSUE TITLE
[RedisInsight] Adding Databases Programmatically couldn't add instance via curl 

### ISSUE THREAD

**Issue by guitarrapc** [RedisLabs/redislabs-docs#1127]
**Current behavior** (A short description of what you found)

When trying to add instance with REST API via curl failed 403 for csrf verification failed.

> doc: https://docs.redislabs.com/latest/ri/using-redisinsight/api/

response

```
<div id="summary">
  <h1>Forbidden <span>(403)</span></h1>
  <p>CSRF verification failed. Request aborted.</p>


</div>
```

**Expected behavior** (A short description of what you expected to find)

successfully add instance.

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

launching redis insight on docker, and tried to sent REST API.

```shell
# save csrf cookie
$ curl -c cookie.txt localhost:8001

# add instance with csrf token
$ curl -X POST -b cookie.txt -H "Content-Type: application/json" -d @body.json http://localhost:8001/api/instance
```

`-H "Cookie: csrftoken=xxxxxxx"` also return same CSRF validation error.

**Comment by banker** [comment]
@slemeur Can you take a look?

**Comment by guitarrapc** [comment]
I've confirm it can do with csrf token pass. It's appreciate if doc advise sample code with cURL access.

```shell
csrf=$(curl -s http://localhost:8001/api/instance -c cookies.txt && cat cookies.txt | cut -f 7 | tail -n 1)
curl -X POST -b cookies.txt -H "Content-Type: application/json" -H "X-CSRFToken:${csrf}" -d '{ "name": "local","connectionType": "STANDALONE","host": "IP ADDRESS OR HOST TO REDIS","port": 6379, "password": "YOUR_PASSWORD" }' http://localhost:8001/api/instance/
```
