### ISSUE TITLE
Platforms - Deploying Kubernetes with Persistent Volumes in Operator-based Architecture Storage spec

### ISSUE THREAD

**Issue by TiloGit** [RedisLabs/redislabs-docs#1200]
Were do you list the requirements for the storage? 
Can we use azure-file storage class (**Provisioner: kubernetes.io/azure-file**) which currently isn't posix compliant?

https://docs.redislabs.com/latest/rs/administering/designing-production/persistent-ephemeral-storage/
and
https://docs.redislabs.com/latest/platforms/kubernetes/concepts/persistent-volumes/

**Comment by amiramm** [comment]
Hi @TiloGit,
Storage requirements are listed under [Hardware Requirements](https://docs.redislabs.com/latest/rs/administering/designing-production/hardware-requirements/#productionenvironment)
For performant production use cases, block storage is required. For example, Azure Disk. Using the premium disk option is recommended. https://kubernetes.io/docs/concepts/storage/storage-classes/#azure-disk

**Comment by TiloGit** [comment]
Thanks for the quick update,. 
So in non production use case, could azure-file work or not due to missing posix compliant?
