### ISSUE TITLE
[RedisInsight] Malware reported in version 1.8.3

### ISSUE THREAD

**Issue by mcacker** [RedisLabs/redislabs-docs#1204]
My organization has pulled me off the network and asked me to remove RedisInsight due to malware being detected again.

I had this problem in the past, but it seems like it was a bug that was fixed, but now it's back.

Threat detected:
- Heur.AdvML.A!400 on usltpf1f7azv - this threat has been observed on this host once in the past 7 days.
C:\Program Files (x86)\RedisInsight\redisinsight.exe, 0A4E5AE137D84AE4E489DEB5043E50F0AE9DE1AD3CC8D72C82C987E539D0E198

**Comment by chenriang1** [comment]
The same thing happened in version 1.10.1.
![image](https://user-images.githubusercontent.com/79974338/128534274-8666e9d0-c0de-44a7-a7fd-d386f1e9d130.png)

Also,
https://www.virustotal.com/gui/file/5a23860e1f1ac0f7f89d6bcfa9d1d5f77ca66e653bd6230caf64e1cd00f5ab84/detection

![image](https://user-images.githubusercontent.com/79974338/128534342-7c35aef4-6df1-4681-a8db-9dc9979391f9.png)

**Comment by alan-wint** [comment]
I just ran into the same issue.  Latest installer of Redis Insight from https://redis.com/redis-enterprise/redis-insight/

**Comment by lanceleonard** [comment]
Hi @mcacker!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
