### ISSUE TITLE
RedisInsight no longer works with Windows Redis 3.0

### ISSUE THREAD

**Issue by mcouillard** [RedisLabs/redislabs-docs#1206]
Newer versions fail to work with windows redis version 3.0 - the most common version windows can use. 
`The 'MEMORY'' command is not supported in the redis instance.`

When using the browser > pick key to view. It works fine when connecting to Redis 3.x and 5.x hosted by Linux.

Older versions of Insight used to work. I'm not sure when it broke. But I've been using Insight since <1.0.

**Comment by K-Jo** [comment]
@nishantgeorge Could we handle the lack of the support better?  @mcouillard can you send a feedback message in the tool about this?  This repository is four our documentation.

**Comment by lanceleonard** [comment]
Hi @mcouillard!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
