### ISSUE TITLE
Redisinsight is not working on my mac machine

### ISSUE THREAD

**Issue by Sourabh25** [RedisLabs/redislabs-docs#1207]
Redisinsight is not launching on my mac

it used to launch normally. It is not working after I update my OS.

os info ; macOS Big Sur 11.1 version

Please let me know if you need any more information

**Comment by GnaneshKunal** [comment]
Hi @Sourabh25, BigSur support has been added.

**Comment by GnaneshKunal** [comment]
@ollopaci This issue can be closed.
