### ISSUE TITLE
Segment analytics stops redisinsight from starting when there is no internet connection 

### ISSUE THREAD

**Issue by mmorel-35** [RedisLabs/redislabs-docs#1228]
**Current behavior** 
Redisinsight seems to require internet access to start. I have the following trace 
``
ERROR:segment:error uploading: HTTPSConnectionPool(host='api.segment.io', port=443): Max retries exceeded with url: /v1/batch (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f9332412d30>: Failed to establish a new connection: [Errno -2] Name or service not known',))
``
I'm using basic configuration, for RIHOST and RIPORT
**Expected behavior**
[Segment](https://github.com/segmentio/analytics-python) seems to be an analytic tool causing the problem. I would like to be able to start without requiring internet access for, analytics reasons. 
The only settings I found were [here](https://docs.redislabs.com/latest/ri/installing/configurations/). Is there an environment variable like RIANALYTICS which could be a boolean enabling or disabling the sending of the usage analytics?

**Comment by mmorel-35** [comment]
@K-Jo , Any idea ?

**Comment by lanceleonard** [comment]
Hi @mmorel-35!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance

**Comment by mmorel-35** [comment]
Hi @lanceleonard,
I didn't know that or I would have published my issue there. 
Thank you for your reactivity.
I'll see if I can find my answer on this repository.
