### ISSUE TITLE
Add support of viewing MsgPack data in RedisInsight

### ISSUE THREAD

**Issue by rsabirov** [RedisLabs/redislabs-docs#1241]
Currently, RedisInstight supports the formatting of JSON (https://docs.redislabs.com/latest/ri/using-redisinsight/java-serialized-objects/), could we get MsgPack support as well? MsgPack is natively supported by Redis Lua.

**Comment by lanceleonard** [comment]
Hi @rsabirov!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
