### ISSUE TITLE
Got a 404

### ISSUE THREAD

**Issue by imitationdave** [RedisLabs/redislabs-docs#1242]
What link led you to our 404 page?
https://docs.redislabs.com/latest/rs/getting-started/redis-enterprise.yaml

Did you find the information you were looking for? If so, on which page?
No, no I am still looking for the example yaml file for deploying Redis on Kubernetes

**Comment by banker** [comment]
@alexmilowski Can you point @imitationdave in the right direction?

**Comment by kaitlynmichael** [comment]
@imitationdave the repo you are looking for is located here: https://github.com/RedisLabs/redis-enterprise-k8s-docs/tree/v6.0.20-4
