### ISSUE TITLE
Popups - annoying

### ISSUE THREAD

**Issue by bionicles** [RedisLabs/redislabs-docs#1253]
**Current behavior** (A short description of what you found)

Three overlapping popups
1. Clippy the nagbot
2. Yes or no satisfied dialog
3. Cookie warning

**Expected behavior** (A short description of what you expected to find)
Docs shouldn't be covered by layers of popups

**Screenshots** (Paste or drag-and-drop a screenshot)
![93579FE7-C41A-4414-BA5A-D66364589E5D](https://user-images.githubusercontent.com/24532336/109446283-63a83c00-7a0f-11eb-884b-7969b44f9e38.png)
![C7402726-D657-4A19-B651-60190EFE5C0C](https://user-images.githubusercontent.com/24532336/109446290-64d96900-7a0f-11eb-8b62-c4536d9810c2.png)

**Additional context** (Add any other information)
Clippy sucks

**Comment by lanceleonard** [comment]
Hi @bionicles!  We hear you.  We're working with marketing to improve the experience.  

We don't have anything to announce at this point, but the popups are definitely part of that conversation.  Stay tuned.

**Comment by bionicles** [comment]
Np, thx for your attention
