### ISSUE TITLE
RedisInsight Bug Redis Cluster replica not showing correct stats after connected to a master

### ISSUE THREAD

**Issue by marksullivancrowd** [RedisLabs/redislabs-docs#1270]
RedisInsight version 1.10.0

After you create a replica in redis cluster under the master-replica nodes the replica node shows "0 keys | 0 B"
inorder to fix it you need to delete the database connection and reconnect it

**Comment by GnaneshKunal** [comment]
Hey @marksullivancrowd, Checking this.

**Comment by lanceleonard** [comment]
Hi @marksullivancrowd!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
