### ISSUE TITLE
Code copy icon is shown in the footer

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#1275]
**Current behavior** (A short description of what you found)
The code copy icon shows in the footer.

**Expected behavior** (A short description of what you expected to find)
That the code copy icon is hidden by the footer

**Screenshots** (Paste or drag-and-drop a screenshot)
![image](https://user-images.githubusercontent.com/19514688/111443000-9e99b780-8711-11eb-8449-f1159a1c22f2.png)

**Additional context** (Add any other information)
Hi y'all

**Comment by lanceleonard** [comment]
Hi Ben!  Thanks for the report.  

Are you reporting this for the RC Getting Started page (rs/getting-started/)?

Also, can you tell me which browser, version, and OS you're using?  (I can't repo on my machine and therefore suspect a markup/CSS issue of some kind.  These details will help direct the troubleshooting.)

Thanks!  Hope everything's well.

**Comment by lanceleonard** [comment]
@bmansheim - Is this still an issue for you?  

If so, would you mind adding the details requested above?  

If not, is it OK to close this issue?

**Comment by lanceleonard** [comment]
Closing, per previous comment.

If the problem recurs, please feel free to reopen or to file a new issue.  (Um, if it does recur, please include the details requested earlier so that we can try to reproduce.)
