### ISSUE TITLE
RedisInsight crashing OSX, forcing login and OS session restart

### ISSUE THREAD

**Issue by brett--anderson** [RedisLabs/redislabs-docs#1279]
**Current behavior** (A short description of what you found)
Downloaded RedisInsight, tried running it from the mounted dmg, also tried dragging it to applications and running it there. After a few seconds I'm booted out of the OS session and have to log in to my mac again as though I just started it

**Expected behavior** (A short description of what you expected to find)
I expected RedisInsight to load so I could play around with RedisGraph and try it out.

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)
macOS Mojave (10.14.6)

System logs matching Redisinsight:
Mar 17 18:35:46 Bretts-MBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.RedisInsight.62858): Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable
Mar 17 18:35:51 Bretts-MBP com.apple.xpc.launchd[1] (com.redislabs.redisinsight.24108[62857]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.
Mar 17 18:37:44 Bretts-MBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.pid.RedisInsight.65061): Could not resolve origin of domain. XPC services in this domain's bundle will not be bootstrapped: error = 107: Malformed bundle, taint = missing executable
Mar 17 18:37:49 Bretts-MBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x1000030b.RedisInsight[65051]): Service did not exit 5 seconds after SIGTERM. Sending SIGKILL.
Mar 17 18:38:01 Bretts-MBP com.apple.xpc.launchd[1] (com.apple.xpc.launchd.oneshot.0x10000316.RedisInsight[65164]): Service exited due to SIGKILL | sent by CoreServicesUIAgent[65167]

**Comment by FriedCircuits** [comment]
Same problem here. Messed me up pretty bad. Lost everything I had running. Not a happy camper right now.

**Comment by leonh** [comment]
Same problem here. Very bad user experience.
Previous versions of Redis Insight have worked with no problem for me.

**Comment by ollopaci** [comment]
Thank you for reporting this issue. We are currently looking into this with the highest priority.

**Comment by leonh** [comment]
Just to confirm **Additional context**. 

I downloaded redisinsight-mac-1.10.0.dmg from the redislabs site today. 
I'm running OSX 10.14.6 on my laptop

**Comment by leonh** [comment]
Any update on this? Where can I download previous versions?
I find redisInsgight to be a useful tool, but  I can only download latest broken release via https://redislabs.com/redis-enterprise/redis-insight/

**Comment by ollopaci** [comment]
We now have a fix for this issue and will be releasing the patch by the end of this week (tentatively tomorrow). Hope this works for you, as previous versions are not so readily available for download.

**Comment by ollopaci** [comment]
RedisInsight v1.10.1 has now been released and it includes the fix for this issue.

**Comment by leonh** [comment]
Thanks for updating on this ticket and getting a new release out to the public. I have just tested and looks good for me.
