### ISSUE TITLE
Does redisinsight v1.10.0 support windows10?

### ISSUE THREAD

**Issue by billyangli** [RedisLabs/redislabs-docs#1297]
I try to install redisinsight v1.10.0  on my pc,WIN10,but it failed.

**Comment by billyangli** [comment]
it shows, this installation package could not be opened.Verify that package exists and that you can access it, or  contact the application dendor to verify that is a valid windows installer package.

**Comment by GnaneshKunal** [comment]
@billyangli Can you provide a screenshot or any logs of the issue you are facing?

**Comment by mmcelwain01** [comment]
My sincere,  thank you to all of you!!! I really appreciate everything everyone has posted and help with!!

**Comment by GnaneshKunal** [comment]
Hi @billyangli, can you try with RedisInsight v1.11?

**Comment by lanceleonard** [comment]
Hi @billyangli!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
