### ISSUE TITLE
Invisible

### ISSUE THREAD

**Issue by dearlove0007cl** [RedisLabs/redislabs-docs#1307]
**Current behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by lanceleonard** [comment]
Hi @dearlove0007cl!  Your issue came in blank.  Please update it so that we can see what the problem is and figure out how to fix it.  Thanks!

**Comment by lanceleonard** [comment]
Without more information to go on, there doesn't seem to be vale in leaving this open.  

If there's still a problem, feel free to reopen and update accordingly.
