### ISSUE TITLE
Need to document how to use Prometheus in the cloud

### ISSUE THREAD

**Issue by TobyHFerguson** [RedisLabs/redislabs-docs#1375]
DELETED - Redislabs JIRA: DOC-726

**Comment by TobyHFerguson** [comment]
This work is related: https://www.google.com/url?q=https://github.com/Redislabs-Solution-Architects/redis-enterprise-cloud-gcp/blob/main/monitoring/monitoring.md&sa=D&source=editors&ust=1621451736991000&usg=AOvVaw2KNOPGqDxq6QCxad6dBdH0

**Comment by kaitlynmichael** [comment]
Closing this issue since it's being tracked in DOC-726
