### ISSUE TITLE
RedisInsight openshift support

### ISSUE THREAD

**Issue by cyberb** [RedisLabs/redislabs-docs#1425]
I am trying to run RedisInsight image on openshift and it deos not seem to work. If I run it locally on plain docker it works fine.

I know openshift has more limitations than a local docker for example a special user id behaviour https://cookbook.openshift.org/users-and-role-based-access-control/why-do-my-applications-run-as-a-random-user-id.html

Can you tell me if openshift is supported?

**Comment by lanceleonard** [comment]
Hi @cyberb; welcome to the docs repo.  

For help with OpenShift, see [Getting started with Kubernetes and OpenShift](https://docs.redislabs.com/latest/platforms/kubernetes/getting-started/openshift/).  

If you need additional help, please file a support ticket.

**Comment by lanceleonard** [comment]
Also, see https://redislabs.slack.com/archives/CBPBES9RB/p1625079560039900 for updates made in RS 6.0.20 (that aren't reflected in the linked doc).

**Comment by lanceleonard** [comment]
(Delete a posted comment accidentally from another thread.  Sorry for the trouble.)

**Comment by cyberb** [comment]
Sorry for not being clear, I am talking specificly about RedisInsight docker image https://hub.docker.com/r/redislabs/redisinsight
It hangs in openshift but runs fine on local docker.
Are you saying it is possible but I have to use Redis Enterprise Operator?

**Comment by lanceleonard** [comment]
I'm merely pointing out that this is the doc repo, not formal support.

Our docs on OpenShift [are here](https://docs.redislabs.com/latest/platforms/kubernetes/getting-started/openshift/).

If you need additional help, please file a support ticket.

**Comment by cyberb** [comment]
Ok, do you know where I can file an issue about RedisInsight docker image?

**Comment by lanceleonard** [comment]
Per the [Redis page](https://hub.docker.com/_/redis) on Docker hub, it looks like you'll want to use https://github.com/docker-library/redis/issues to file issues with the Docker images.

**Comment by cyberb** [comment]
Thanks, https://github.com/docker-library/redis/issues/284

**Comment by cyberb** [comment]
They said:
```
redislabs/redisinsight is their own maintained image that the Docker Official Images team isn't involved with
```

**Comment by cyberb** [comment]
> If you need additional help, please file a support ticket.

Where can I do this?
Do I need to buy a license to do that?

**Comment by lanceleonard** [comment]
If you have an account on the Redis Enterprise Cloud [admin console](https://app.redislabs.com), you can add a support ticket after signing in.

Alternate support options are listed at https://redislabs.com/company/support/

**Comment by GnaneshKunal** [comment]
@cyberb, can you share the RedisInsight container logs?

**Comment by cyberb** [comment]
Sorry it actually worked in the end, it was an issue on our side.
