### ISSUE TITLE
Adding Databases Programmatically - disable Verify TLS Certificate

### ISSUE THREAD

**Issue by NickSalter** [RedisLabs/redislabs-docs#1496]
When adding a database via the GUI the option 'Verify TLS Certificate' can be disabled however looking at the documentation (<https://docs.redis.com/latest/ri/using-redisinsight/api/#tls-parameters>) this doesn't appear to be possible via the api. Is there an undocumented parameter to do this? 

When trying to add a database via the api with TLS enabled I get the below error:

{"errCode":"REDIS_CONNECTION_ERROR","msg":"Could not connect: Error 1 connecting to 10.0.0.4:6379. [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)."}

**Comment by GnaneshKunal** [comment]
Hey @NickSalter, you can pass `verifyServerCert` and set it to `false`.

**Comment by NickSalter** [comment]
That worked! Thanks very much for taking the time to reply.
