### ISSUE TITLE
RedisInsight Zset can't show full content

### ISSUE THREAD

**Issue by ahkui** [RedisLabs/redislabs-docs#1618]
Can't preview JSON Content when key type is `zset`

> `.data.command` is php serialize data

![image](https://user-images.githubusercontent.com/14049597/138436713-e11282fb-94c9-4697-8026-b8809f923f8b.png)

**Comment by GnaneshKunal** [comment]
Hey @ahkui, Thanks for reporting. We are looking into it.

**Comment by lanceleonard** [comment]
Hi @ahkui!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
