### ISSUE TITLE
rladmin status output shows extra characters junk characters. This is creating issues for creating health check reports manually

### ISSUE THREAD

**Issue by sibuv** [RedisLabs/redislabs-docs#1655]
**Current behavior** (A short description of what you found)

**Expected behavior** (A short description of what you expected to find)

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by sibuv** [comment]
I cannot paste the full output .But a sample of the output is as below.

[?1034h[1mCLUSTER NODES:[0m
[1m[4mNODE:ID ROLE   ADDRESS     EXTERNAL_ADDRESS HOSTNAME               SHARDS CORES FREE_RAM     PROVISIONAL_RAM VERSION   STATUS[0m
[36m*node:1 slave  254.4.7.148               

I am worried about these characters in the output and processing output using perl in linux. These extra characters is creating issues in writing regular expression to fetch the desired values. By the way, I am writing  a script to do a health check to include rladmin status, persistent mount point space details etc. What I am trying to do is to create a single perl script to get the health details of multiple redis clusters.

**Comment by lanceleonard** [comment]
Hi @sibuv - I'm afraid you'll need to [reach out to Support](https://redis.com/company/support/) for help with this.

**Comment by lanceleonard** [comment]
Hi @sibuv!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
