### ISSUE TITLE
Unclear Documentation

### ISSUE THREAD

**Issue by utsavtulsyan** [RedisLabs/redislabs-docs#1657]
**Current behavior** (A short description of what you found)

```
bdb_avg_latency | Average latency of operations on the DB (seconds); returned only when there is traffic
-- | --
bdb_avg_latency_max | Highest value of average latency of operations on the DB (seconds); returned only when there is traffic
```

What is the the two latency, what does highest signify? How is it calculated from the normal metric?

**Expected behavior** (A short description of what you expected to find)
Clear explanation of the terms used.

**Screenshots** (Paste or drag-and-drop a screenshot)
NA

**Additional context** (Add any other information)
https://github.com/RedisLabs/redislabs-docs/blob/master/content/rs/administering/monitoring-metrics/prometheus-metrics-definitions.md

**Comment by lanceleonard** [comment]
@utsavtulsyan - Thanks for the report; we'll look into it.  If you need immediate help, please [reach out to support](https://redis.com/company/support/)

**Comment by lanceleonard** [comment]
Hi @utsavtulsyan!

We've recently published a new page detailing the [database metrics](https://docs.redis.com/latest/rs/references/rest-api/objects/statistics/db-metrics/).  Take a look.

I'm closing this issue in the mean time.  If you still need help, feel free to [reach out to support](https://redis.com/company/support/) or to post a follow up question on our [Discord server](https://discord.gg/redis).
