### ISSUE TITLE
More detail about backup files would be helpful

### ISSUE THREAD

**Issue by gmflau** [RedisLabs/redislabs-docs#1685]
**Current behavior** (A short description of what you found)
Some customers reported that it is confusing to see more than one backup rdb.gz files being generated when backing up a single database. (https://docs.redis.com/latest/rc/databases/back-up-data/)

**Expected behavior** (A short description of what you expected to find)
It would be helpful to describe the 1:1 ratio between #shards of a database to #rdb.gz backup files.

**Screenshots** (Paste or drag-and-drop a screenshot)
N/A

**Additional context** (Add any other information)
None

**Comment by lanceleonard** [comment]
Hi @gmflau - per our private discussion, this will be tracked internally (DOC-1028).
