### ISSUE TITLE
How to import backup files for multi-shard database

### ISSUE THREAD

**Issue by gmflau** [RedisLabs/redislabs-docs#1686]
**Current behavior** (A short description of what you found)
Currently, the documentation (https://docs.redis.com/latest/rc/databases/import-data/) to import back files for a multi-shard database.  It only tells how to import a single db.gz file.

**Expected behavior** (A short description of what you expected to find)
It would be helpful the documentation to share instructions how to handle an import of backup files for a multi-shard database.

**Screenshots** (Paste or drag-and-drop a screenshot)
N/A

**Additional context** (Add any other information)
None

**Comment by lanceleonard** [comment]
Hi @gmflau - per our private discussion, this will be tracked internally (DOC-1028).
