### ISSUE TITLE
Update node-redis Documentation to v4

### ISSUE THREAD

**Issue by russ-lewis** [RedisLabs/redislabs-docs#1690]
**Current behavior**

Gives example code which is correct for node-redis 3.x but which fails (that is, silently fails to do anything) on 4.0.  As of 8 days ago, 4.0 is current in npm.

**Expected behavior**

Website should show both v3 and v4 code examples.

**Additional context**

Please note that I've added an issue in node-redis, asking them to give error messages to make this easier to find; however, hopefully the documentation on this website can be improved as well.  https://github.com/redis/node-redis/issues/1762

**Comment by lanceleonard** [comment]
@russ-lewis - Thanks for the report; we'll see what we can do.

Have you seen the [developer.redis.com](https://developer.redis.com/) info [on node-redis](https://developer.redis.com/develop/node/gettingstarted)?  It looks to be a bit more up-to-date.  Also, take a look at the new [Redis-OM library for Node.js](https://developer.redis.com/develop/node/redis-om). 

If you need further help, the [Redis Discord server](https://developer.redis.com/community/discord) is a good option.

**Comment by lanceleonard** [comment]
Hi @russ-lewis! 

We've added an item to our internal backlog to handle this work, as there's a bit of coordination and conversation that needs to take place.  In the mean time, I'm closing this issue.

If you're still having trouble, please feel free to follow up in the Discord server or to follow up o the issue that you filed in https://github.com/redis/node-redis/
