### ISSUE TITLE
Command segments need formatting

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#261]
**Expected behavior** (A concise description of what you found)
There are command segments in the text on https://docs.redislabs.com/latest/rs/administering/security/client-connections/ that aren't formatted as code.

**Expected behavior** (A concise description of what you expected to find)
All command and code segments should be in `backticks`.

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by ayruslore** [comment]
Opened a pull request to resolve the issue.
Pull Request Link - https://github.com/RedisLabs/redislabs-docs/pull/1197

**Comment by bmansheim** [comment]
Good form, @ayruslore . Thank you for jumping in to help us with this.
