### ISSUE TITLE
bad link in Getting Started with Kubernetes and OpenShift

### ISSUE THREAD

**Issue by carolynsims** [RedisLabs/redislabs-docs#300]
**Expected behavior** (A concise description of what you found)
On https://docs.redislabs.com/latest/rs/getting-started/k8s-openshift/#step-5-create-a-database Getting Started with Kubernetes and OpenShift, the "3. The OpenShift cli installed"
link goes to https://www.rubix.nl/blogs/how-install-and-run-openshift-origin-your-mac-os-x
This is a dead link on a site in the Netherlands...

**Expected behavior** (A concise description of what you expected to find)
It would be better for it to go to https://docs.openshift.com/online/cli_reference/get_started_cli.html
It would also be better to do a screenshot (similar to the ones below that are there already) but showing where you can download it from, e.g. for free with a trial (vs needing a subscription to RHEL to access it otherwise).   Add a red oval around the "Command Line Tools".

**Screenshots** (If applicable, add screenshots of the problem)

![openshift origin cli](https://user-images.githubusercontent.com/47534495/54792920-6c761d80-4bfd-11e9-9a47-53dcd6c3c78a.png)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Good catch, @carolynsims! I'll put it into the queue.

**Comment by bmansheim** [comment]
Hey, @amiramm . The link to rubix works for me but do we want to change it to the openshift CLI Getting Started as @carolynsims recommended?

**Comment by amiramm** [comment]
Make sense to point to OpenShift documentation. **Note** this is the correct link: https://docs.openshift.com/container-platform/4.1/cli_reference/getting-started-cli.html

**Comment by bmansheim** [comment]
Resolved in: https://github.com/RedisLabs/redislabs-docs/pull/413

**Comment by bmansheim** [comment]
> Make sense to point to OpenShift documentation. **Note** this is the correct link: https://docs.openshift.com/container-platform/4.1/cli_reference/getting-started-cli.html

@amiramm Do you want it to link specifically to the 4.1 version of the article or to whatever is the latest?
