### ISSUE TITLE
Missing picture @ ReBloom page

### ISSUE THREAD

**Issue by AlonMagrafta** [RedisLabs/redislabs-docs#339]
**Current behavior** 
Missing picture on 
https://docs.redislabs.com/latest/rs/developing/modules/bloom-filters/

**Expected behavior** (rebloom-hash1 picture)

**Screenshots** (If applicable, add screenshots of the problem)
![image](https://user-images.githubusercontent.com/50071256/56954037-7cf7ad00-6b46-11e9-9dcd-2c254ca2533a.png)

**Comment by bmansheim** [comment]
https://github.com/RedisLabs/redislabs-docs/pull/341
