### ISSUE TITLE
Update module names to RedisJSON and RedisBloom

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#369]
**Current behavior** (A concise description of what you found)
in https://docs.redislabs.com/latest/index.html the modules links still show old module names “ReJson” instead of RedisJSON and “ReBloom” instead of RedisBloom. Please fix.

**Expected behavior** (A concise description of what you expected to find)
All pages use the updated names, RedisJSON and RedisBloom.

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
@K-Jo FYI

**Comment by K-Jo** [comment]
To be complete it should also be RedisGraph RediSearch RedisTimeSeries RedisAI and RedisGears
I would however wait till we have fixed RED-27583 @Paz-Yanover

**Comment by Paz-Yanover** [comment]
@bmansheim - let's wait

**Comment by bmansheim** [comment]
Preparing changes in https://github.com/RedisLabs/redislabs-docs/pull/409

**Comment by bmansheim** [comment]
Merged in #409
