### ISSUE TITLE
Rewrite K8s getting started doc (docker/GCP)

### ISSUE THREAD

**Issue by amiramm** [RedisLabs/redislabs-docs#415]
**Current behavior** (A concise description of what you found)
 https://github.com/RedisLabs/redislabs-docs/blob/master/content/platforms/kubernetes/_index.md
Is misleading, needs to be removed.
This doesn't use RedisLabs Operator deployment and erroneously indicates it is not production worthy. 

**Expected behavior** (A concise description of what you expected to find)
There need to be two separate articles, one for Docker (already available in RS section) and one for GCP which accurately described the supported deployment.

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
In https://github.com/RedisLabs/redislabs-docs/pull/417, the K8s getting started content is in comment.

After the content is rewritten and published, this issue can be closed.

**Comment by alexmilowski** [comment]
I feel like [PR 1007](https://github.com/RedisLabs/redislabs-docs/pull/1007) addresses the generic K8s setup (GKE, etc.). We need better leading intros for each supported platforms that directs the user to use the right guide.

**Comment by kaitlynmichael** [comment]
This will be resolved as part of the K8s refresh project (DOC-532)
