### ISSUE TITLE
Kubernetes FAQ section needs to be moved from RS to Platforms

### ISSUE THREAD

**Issue by amiramm** [RedisLabs/redislabs-docs#416]
**Current behavior** (A concise description of what you found)
FAQ for Kubernetes is under general FAQ in RS section of the documentation

**Expected behavior** (A concise description of what you expected to find)
FAQ for Kubernetes should be under the Platform section

**Screenshots** (If applicable, add screenshots of the problem)
![Screen Shot 2019-06-11 at 3 45 07 PM](https://user-images.githubusercontent.com/7783341/59312026-5f972200-8c60-11e9-8317-1cefb4dee497.png)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Resolved in https://github.com/RedisLabs/redislabs-docs/pull/417
