### ISSUE TITLE
Add more clues for customers to find UI elements in RC Pro

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#428]
**Current behavior** (A concise description of what you found)
I want to report additional usability improvement that I think it needed in our Cloud Pro section https://docs.redislabs.com/latest/rv/administration/setup_and_editing/view-edit-subscription/ - for example finding the + sign in VPC Peering screen is not trivial and showing it on a screenshot creates a much better reference to customers.

**Expected behavior** (A concise description of what you expected to find)
I believe some screenshots of actual UI would help

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by banker** [comment]
No longer applicable.
