### ISSUE TITLE
Update how to configure custom local logging policy.

### ISSUE THREAD

**Issue by IAmATeaPot418** [RedisLabs/redislabs-docs#450]
**Current behavior** (A concise description of what you found)
We do not currently document how to customize the logging configuration if required.

**Expected behavior** (A concise description of what you expected to find)
Some organizations may have custom logging policies that require retention policies longer or shorter than out of the box provides.

**Screenshots** (If applicable, add screenshots of the problem)
N/A

**Additional context** (Add any other information)
Document how to update leveraging logrotate.d

**Comment by banker** [comment]
Moving to internal JIRA.
