### ISSUE TITLE
Change upgrade note for each minor version

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#463]
**Current behavior** (A concise description of what you found)
The first warning in the upgrade page says to check the release notes of the initial version release.
https://docs.redislabs.com/latest/rs/installing-upgrading/upgrading/

**Expected behavior** (A concise description of what you expected to find)
Must be updated to refer to the last minor version of the release.

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by banker** [comment]
This is addressed here: https://github.com/RedisLabs/redislabs-docs/pull/1252
