### ISSUE TITLE
Indentation on REC spec is wrong in PKS getting started article

### ISSUE THREAD

**Issue by amiramm** [RedisLabs/redislabs-docs#467]
**Current behavior** (A concise description of what you found)

https://github.com/RedisLabs/redislabs-docs/tree/pks-getting-started/content/platforms/pks
_index

REC spec in redis_enterprise_cluster.yaml code snippet is indented wrong and needs to be amended.

**Expected behavior** (A concise description of what you expected to find)

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
This change is still in a PR and not published so I'll follow it without the issue.
