### ISSUE TITLE
Docs are not listed in website search

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#473]
**Current behavior** (A concise description of what you found)
When you search in the redislabs.com website, you don't see the results from the docs. This frustrates users. Although less than 1% of our pageviews on the marketing site use the site search, most of those searches are for technical keywords and cause bad UX.

**Expected behavior** (A concise description of what you expected to find)
Search on the website should include docs

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Task for marketing team

**Comment by banker** [comment]
Moving to internal JIRA.
