### ISSUE TITLE
Automatically add staging link to PRs

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#474]
**Current behavior** (A concise description of what you found)
PRs opened on the repo spin up a staging site but there is no link to the staging site provided.

**Expected behavior** (A concise description of what you expected to find)
PRs opened on the repo have the link to the staging site automatically add to the PR.

**Screenshots** (If applicable, add screenshots of the problem)

**Additional context** (Add any other information)

**Comment by banker** [comment]
Moving to internal JIRA.
