### ISSUE TITLE
RedisInsight Security

### ISSUE THREAD

**Issue by IAmATeaPot418** [RedisLabs/redislabs-docs#542]
Document a list of security-relevant considerations to simply guide our customers and help teams with security considerations.

**Comment by rromanchuk** [comment]
**re redisinsight**: securing this is a PITA for small companies that collaborate in clear net. My SSL is terminated at the load balancer, but It would be nice if i could supply an `ENVIRONMENT` variable for at least basic http auth, that could be passed to the docker install.


https://github.com/RedisLabs/redislabs-docs/blame/master/content/ri/faqs.md#L135

There's also a reference to an undocumented "admin password" but maybe that's leaking in from another product? 

> How can I secure my RedisInsight installation?
> We recommend installing HTTPS, whitelisting IP addresses that have access to RedisInsight and/or making it available within your VPN/internal network. Additionally, choose a strong admin password.
>

**Comment by banker** [comment]
Thanks for the feedback @rromanchuk. @slemeur Can you respond to this?

**Comment by bmansheim** [comment]
Hi @rromanchuk . That's referring to the admin password on the database. I'll change it to make it more explicit.

**Comment by lanceleonard** [comment]
Hi @IAmATeaPot418 and @rromanchuk! 

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
