### ISSUE TITLE
Import modules capabilities according to version

### ISSUE THREAD

**Issue by bmansheim** [RedisLabs/redislabs-docs#596]
**Current behavior** (A short description of what you found)
Each module per version has a different list of supported RS features and they are listed in the ramp.yml file in the module repository. Those capabilities are not listed in the documentation.

**Expected behavior** (A short description of what you expected to find)
Each module should have its documentation versioned and include the of supported RS features from the ramp.yml file.

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by banker** [comment]
This is being tracked internally.
