### ISSUE TITLE
Storage *can* be configured, but how? Need link!

### ISSUE THREAD

**Issue by TobyHFerguson** [RedisLabs/redislabs-docs#605]
**Current behavior** (A short description of what you found)
On [Persistent and Ephemeral Storage](https://docs.redislabs.com/latest/rs/administering/designing-production/persistent-ephemeral-storage/) it says 

> For each node in the cluster, you can configure both a persistent storage and an ephemeral storage path.

but there're no links to explain exactly how to accomplish that task

**Expected behavior** (A short description of what you expected to find)
One or more links that show exactly how this storage is configured. A run-book, if you will. At least a worked example. 

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by kaitlynmichael** [comment]
Moving this issue to Jira (DOC-752)
