### ISSUE TITLE
REST API is hidden. Should be exposed in table of contents

### ISSUE THREAD

**Issue by TobyHFerguson** [RedisLabs/redislabs-docs#606]
**Current behavior** (A short description of what you found)
REST API is documented in a note on the [Administering Redis Enterprise](https://docs.redislabs.com/latest/rs/administering/) page. It can't be found by looking at the table of contents (ToC), but is nevertheless (in my opinion!) sufficiently important that it should be present in the ToC

**Expected behavior** (A short description of what you expected to find)
That the REST API not is promoted to a subsection, which can easily found in the ToC

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by kaitlynmichael** [comment]
This issue is being tracked in Jira (DOC-750)
