### ISSUE TITLE
RedisInsight  can not start normally

### ISSUE THREAD

**Issue by gogotanc** [RedisLabs/redislabs-docs#639]
**Current behavior** (A short description of what you found)

My mac crashed unexpectedly, RedisInsight was running background then.

When I reboot my mac, RedisInsight can not start normally.

**Expected behavior** (A short description of what you expected to find)

I reinstall RedisInsight, but do not work.

how to fix it? where is the log?

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

here are some info.

- MacBook Pro (15-inch, 2019)
- macOS Catalina 10.15.2
- RedisInsight v1.10

thx.

**Comment by K-Jo** [comment]
@nishantgeorge

**Comment by nishantgeorge** [comment]
@gogotanc 

> where is the log?

https://docs.redislabs.com/latest/ri/using-redisinsight/troubleshooting/#logs

> how to fix it?

Could you check using the Activity Monitor whether there are any RedisInsight processes running and if so, kill all of them and try running RedisInsight again?

**Comment by gogotanc** [comment]
@nishantgeorge 

it works, thx. 👍

i find a RedisInsight process in the Activity Monitor, i killed it, and run again.
