### ISSUE TITLE
Kubernetes service env vars conflicting with pods

### ISSUE THREAD

**Issue by araza142** [RedisLabs/redislabs-docs#676]
**Current behavior** (A short description of what you found)
K8s deployment without exposing service works fine. But when adding a service to expose, it causes conflicts with pod env vars and pod fails to start. Tried skipping the service vars using `enableServiceLinks: false` which started the pod but its giving EMPTY RESPONSE on URL.

**Error** (Paste or drag-and-drop a screenshot)
`Starting system message bus: dbus.
Starting Avahi mDNS/DNS-SD Daemon: avahi-daemon.
INFO 2020-02-10 18:00:16,597 redisinsight_startup Registered SIGTERM handler
ERROR 2020-02-10 18:00:16,610 redisinsight_startup Error in main()
Traceback (most recent call last):
  File "./startup.py", line 470, in main
ValueError: invalid literal for int() with base 10: 'tcp://10.100.74.69:80'
Traceback (most recent call last):
  File "./startup.py", line 488, in <module>
  File "./startup.py", line 470, in main
ValueError: invalid literal for int() with base 10: 'tcp://10.100.74.69:80'`

**Comment by araza142** [comment]
Declaring env vars fixed it:
`env:
          - name: REDISINSIGHT_HOST
            value: "0.0.0.0"
          - name: REDISINSIGHT_PORT
            value: "80"`

**Comment by bmansheim** [comment]
@araza142 I'm glad you found an easy solution!

**Comment by guitarrapc** [comment]
it help me so match. thank you for great workaround.

**Comment by laurentdroin** [comment]
@araza142 @guitarrapc - could you let us know how you deployed RedisInsight on Kubernetes? Did you follow the procedure described at https://docs.redislabs.com/latest/ri/installing/install-k8s/ ?
or did you follow a different procedure? And in this case, can you share it with us?
Also, was your K8S environment an Openshift environment ?

**Comment by guitarrapc** [comment]
@laurentdroin ok.

> Did you follow the procedure described at https://docs.redislabs.com/latest/ri/installing/install-k8s/ ?

yes, but official instruction missing consideration for svc, so you must put additional `env` as @araza142 shared in https://github.com/RedisLabs/redislabs-docs/issues/676#issuecomment-586077122 

> did you follow a different procedure

no. you don't need.

> And in this case, can you share it with us?

here's k8s deployment with service sample for you. https://github.com/guitarrapc/k8s-lab/blob/master/redis/k8s/deployment.yaml

> was your K8S environment an Openshift environment ?

k8s with service.

**Comment by laurentdroin** [comment]
Hi @guitarrapc - Thank you for the update. It is very useful and I now understand the issue better.
There is indeed a conflict between the environment variables we use and the ones created by Kubernetes when a service is created. The names of the variables are derived from the name of the service.
We are going to look into this and see how it can be addressed properly.

In the meantime, other workarounds would be to use a different name for your service (for example redisinsight-svc) or to create the deployment before the service.

**Comment by Rubyan** [comment]
This also solved my issue when deploying on Openshift (OKD)
