### ISSUE TITLE
Document MFA in RC

### ISSUE THREAD

**Issue by IAmATeaPot418** [RedisLabs/redislabs-docs#677]
We haven't documented MFA capabilities in RC. RC currently supports MFA capabilities but this is undocumented functionality. This is minor and I'll probably submit a PR for this next week. Documenting the issue for now.

**Comment by bmansheim** [comment]
FYI @Aviad-Abutbul . I'll open a docs ticket.

**Comment by IAmATeaPot418** [comment]
Resolved and Closed by https://github.com/RedisLabs/redislabs-docs/pull/702
