### ISSUE TITLE
[securityalert / malware / redisinsight - win!] Malware Trojan inside Redisinsight

### ISSUE THREAD

**Issue by ibrainventures** [RedisLabs/redislabs-docs#679]
May its wrong inside this git-section - but cant find a other way for security alerts.

Downloaded 2 days ago the redisinsight win edition over the redislabs website.

Today all malware finders are going high and give a high secruity alert.

![grafik](https://user-images.githubusercontent.com/8803626/74229813-6a102c80-4cc3-11ea-9bb4-5e359045af1c.png)

Also on some stackoverflow disussions.

https://stackoverflow.com/questions/60151517/redisinsight-contains-malware

Please give a response or update for this issue.

**Comment by ibrainventures** [comment]
some updates on a reddit thread

https://www.reddit.com/r/redis/comments/f1qapz/redisinsight_cotains_malware/

https://www.virustotal.com/gui/file/d8935449f89bb8a859542bc72e553e3d4c2d1107615f6796b693c1351e0c2331/details

**Comment by banker** [comment]
@ibrainventures Thanks for reporting this. We'll get back to you (cc @K-Jo)

**Comment by K-Jo** [comment]
Hi @ibrainventures, thanks for reporting, we are on top of this issue.  It is related to pyinstaller https://github.com/pyinstaller/pyinstaller/issues/4633.  We plan to release a fix very soon and you will get an upgrade notification within RedisInsight

**Comment by gnaneshr** [comment]
@ibrainventures 
A new version of RedisInsight (v1.2.2) just got released and had this fixed.

**Comment by bmansheim** [comment]
@ibrainventures It seems that the issue was resolved with a new release so I'm closing this issue as invalid because there is no documentation change required.
Thanks for reporting!
