### ISSUE TITLE
redisinsight change the IP and port

### ISSUE THREAD

**Issue by EsCool** [RedisLabs/redislabs-docs#691]
I have a problem when I use redisinght:
**OS: Linux (not desktop)
Version:1.2.2**
my redis server in running in local area network.  
Due to poor performance of my PC, I deploy the redisinsght in a linux server which IP address is 10.20.20.15.  But when I start redisinsight, it running on 127.0.0.1 and 8001. how can I change the IP to my PC can access IP like 10.20.20.15. 
then I can use my PC to browser 10.20.20.15:8001 to use redisinsight

anyone can help me?
thank u !!!

**Comment by bmansheim** [comment]
@EsCool Thanks for contacting us. @K-Jo and @nishantgeorge, can you help with this?

**Comment by slemeur** [comment]
Hi @EsCool ! 
Thanks for reaching out with your question.

You can completely configure those settings by changing the environment variables.
We have documentation about that available here: https://docs.redislabs.com/latest/ri/installing/configurations/

Hope this helps.
