### ISSUE TITLE
Has the doc been added for the features discussed at RedisConf19

### ISSUE THREAD

**Issue by sudipt1999** [RedisLabs/redislabs-docs#711]
I am working on a project that uses RedisGraph and for improving the query mechanism and storage and I came across https://www.youtube.com/watch?v=PTL7aRPFKt8 (RedisConf19) which showed few new features :-
1. Graph API
2. Graph Aided Search
3. Full Graph Search 
so I looked for the docs but haven't found any! Kindly let me know where they are.

**Comment by bmansheim** [comment]
Thanks for checking with us @sudipt1999 . Maybe @K-Jo can help answer your question.

**Comment by K-Jo** [comment]
@sudipt1999 this is actually a question for https://github.com/RedisGraph/RedisGraph/
1. we are still working on this
2. yes it has been released in redisgraph 2.0 and we'll publish a blog about this soon
3. If this relates to the full graph response.  Yes this is in place as well.  You can try it out on >2.0 versions and with RedisInsight https://redislabs.com/redisinsight/
