### ISSUE TITLE
RS - Installing Redis Enterprise Software

### ISSUE THREAD

**Issue by goranceko** [RedisLabs/redislabs-docs#733]
**Current behavior** (A short description of what you found)
Clicking the Kubernetes link https://docs.redislabs.com/latest/platforms/kubernetes/.md leads to a 404 page: https://docs.redislabs.com/latest/rs/installing-upgrading/ 

**Expected behavior** (A short description of what you expected to find)
Being able to navigate to the Kubernetes page. 

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by banker** [comment]
Thanks for the report! We'll get this fixed.

**Comment by bmansheim** [comment]
Great catch, @goranceko. It's fixed now.
