### ISSUE TITLE
Redisinsights not compatible with Google Cloud memorystore redis instances

### ISSUE THREAD

**Issue by abdomazzika** [RedisLabs/redislabs-docs#734]
When i added my memorystroe instance to redisinsights it gives me this error message
```bash
The '`CLIENT`, with args beginning with: `SETNAME`, `RedisInsight`, ' command is not supported in the redis instance.
```
![Screen Shot 2020-04-12 at 4 54 24 PM](https://user-images.githubusercontent.com/16388665/79070423-6fe3b780-7cde-11ea-96b5-6daa635660e7.png)

**Comment by ClaytonOlleyITN** [comment]
Any updates on this by chance? I'm running into similar issues.

**Comment by lanceleonard** [comment]
Hi @abdomazzika and @ClaytonOlleyITN! 

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
