### ISSUE TITLE
RedisInsight installation on windows is still being detected as malware 

### ISSUE THREAD

**Issue by mrm-robotack** [RedisLabs/redislabs-docs#737]
the RedisInsight even on version 1.3 is still being detected as including a malware on windows. The detection has been done by both bitdefender antivirus and the anti malware service on windows.

**Comment by banker** [comment]
Thanks for the report. @K-Jo Can you respond?

**Comment by slemeur** [comment]
@mrm-robotack : Thanks for reporting the issue. 
Would you be able to attach a screenshot of the message that is attached? 
Also what is the version you installed? 

According to VirusTotal, the msi file for 1.3.1 is not supposed to show any warning from bitdefender: https://www.virustotal.com/gui/file/b7dae2835df32fd38d6cb3b403e784a166ad9e31d03a4c9f624f1a2a2d4812d9/detection

**Comment by mrm-robotack** [comment]
Hi .. It's version 1.3.0 .. it's the default that was available from the website on 12/4/2020. I'll check if a newer version is available and update if it is solved.

**Comment by mrm-robotack** [comment]
Well yeah I just installed version 1.3.1 and it's running normally. Thanks a lot.

**Comment by slemeur** [comment]
Really glad to her @mrm-robotack ! 
Thanks again for reaching out and reporting the issue.
Appart from this issue, how have been your experience with RedisInsight so far ?
