### ISSUE TITLE
RediSearch Module: broken image link to redisearch_partitions.png

### ISSUE THREAD

**Issue by tgrall** [RedisLabs/redislabs-docs#770]
**Current behavior** 

An image is missing in page:
https://docs.redislabs.com/latest/modules/redisearch/

See line 146 : `![redisearch_partitions](/images/rs/redisearch_partitions.png?width=700&height=119)`

**Expected behavior** 

Upload the image or remove the image from the page

**Comment by bmansheim** [comment]
So glad you pointed this out, @tgrall . Will put it into our tasks.

In general, how has your experience been with the docs?
