### ISSUE TITLE
What is an Operator section describes StatefulSets as good for stateless applications

### ISSUE THREAD

**Issue by andresrinivasan** [RedisLabs/redislabs-docs#824]
**Current behavior** (A short description of what you found)

In [What is an Operator?](https://docs.redislabs.com/latest/platforms/kubernetes/kubernetes-with-operator/#what-is-an-operator) StatefulSets are described as good for stateless applications. In contrast the [StatefulSets documentation](https://kubernetes.io/docs/concepts/workloads/controllers/statefulset/) says 

> StatefulSet is the workload API object used to manage stateful applications.

**Expected behavior** (A short description of what you expected to find)

Something more consistent with the K8s documentation. Apparently there is a weakness in StatefulSets that limits their usefulness to Redis Enterprise but I don't understand what the issue is.

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Thanks for your comment @andresrinivasan.
@alexmilowski, can you comment on this?

**Comment by kaitlynmichael** [comment]
Moving this issue to Jira (DOC-751)
