### ISSUE TITLE
how can i connect to Standalone Redis with ssh tunnel by redis insight

### ISSUE THREAD

**Issue by likemoongg** [RedisLabs/redislabs-docs#825]
I watch the [doc](https://docs.redislabs.com/latest/ri/using-redisinsight/add-instance/) and cann't found the way to conenct to standalone redis within ssh tunnel，did RedisInsight has the feature and will add the feature in the future ?

**Comment by bmansheim** [comment]
Hi @likemoongg . Thanks for reaching out. I'll check on your issue and see what I find.

**Comment by feketegy** [comment]
RedisInsight doesn't support ssh tunneling out of the box as far as I know. I had to manually open an ssh tunnel and connect to that. 

You can open an SSH tunnel like so: `ssh -L<localPort>:localhost:<remotePort> <remoteUser>@<remoteServer>`, for example: `ssh -L 36379:localhost:6379 myuser@myserver.net`. My remote Redis is listening on 6379 and tunneled it through to 36379.


As long as the tunnel is open you can create a new Redis database in RedisInsight by connecting to 127.0.0.1 and port 36379.

**Comment by GnaneshKunal** [comment]
@likemoongg 

The steps mentioned by @feketegy is the way to go. RedisInsight has no plans to add tunnel support since it is usually done out of the application.

**Comment by GnaneshKunal** [comment]
@ollopaci This issue can be closed!
