### ISSUE TITLE
Shutting Down a node: make it clear at the beginning that only one node at the time should be stopped

### ISSUE THREAD

**Issue by tgrall** [RedisLabs/redislabs-docs#828]
**Current behavior** (A short description of what you found)

In the page: https://docs.redislabs.com/latest/rs/administering/cluster-operations/shutting-down-node/

Some customers miss the last sentence and misunderstand it:

| Note: You should only shut down one node at a time.

**Expected behavior** (A short description of what you expected to find)

* we should put this information at the beginning at the page
* make it clear that only 1 node should be stopped at a time. Some non native speaker understood it as you have to stop the nodes one after the other. 
 
* we should say that:
   * a cluster should not be stopped
   * all maintenance operations should be done in a Rolling way

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Hi @tgrall . Thanks for the issue. Can you review https://github.com/RedisLabs/redislabs-docs/pull/829 and tell me what you think?

**Comment by bmansheim** [comment]
Resolved in #829
