### ISSUE TITLE
RCU on GCP-Marketplace doesn't have "Settings"->"Team" tab

### ISSUE THREAD

**Issue by ruslan-redislabs** [RedisLabs/redislabs-docs#843]
**Current behavior** (A short description of what you found)
Would worth mentioning that GCP-marketplace doesn't have Settings->Team tab and instead managed outside of SM, in GCP with some how-to or link, if there is.

**Expected behavior** (A short description of what you expected to find)
https://docs.redislabs.com/latest/rc/administration/account-team-settings/#team-management would have a note on GCP behavior, with details if possible.

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Resolved in https://github.com/RedisLabs/redislabs-docs/pull/845
