### ISSUE TITLE
Using RedisInsight behind a reverse proxy

### ISSUE THREAD

**Issue by eexwhyzee** [RedisLabs/redislabs-docs#855]
**Current behavior** (A short description of what you found)
Followed these instructions to deploy RedisInsight on k8s: https://docs.redislabs.com/latest/ri/installing/install-k8s/

RedisInsight works correctly when not using a path rewrite via reverse proxy, but when trying to do a path rewrite with a specific prefix, the UI won't load correctly because it is expecting a js bundle at `/` instead of the prefix specified on the rewrite rule.

**Expected behavior** (A short description of what you expected to find)
There should be some type of configuration option to specify a prefix URL when using a reverse proxy, but so far i wasn't able to find any option to do that (these are the only configuration options listed in the docs: https://docs.redislabs.com/latest/ri/installing/configurations/#redisinsight-environment-variables)

**Comment by bmansheim** [comment]
Hi @eexwhyzee . Glad you pointed that out!
@slemeur What are your thoughts?

**Comment by eexwhyzee** [comment]
@bmansheim just wanted to check in on this issue, really excited to start using this tool!

**Comment by slemeur** [comment]
Hi @eexwhyzee !
Thanks for reaching out and letting us know about your issue and the way you would like to run RedisInsight.

We'll add the configuration option so that you can prefix the URL when using a reverse proxy.

**Comment by davidpelfree** [comment]
I think using relative web URLs will be good enough. It will be "reverse proxy compatible" by default. 

Why not avoid using additional environment variable if possible?

**Comment by samcarpentier** [comment]
@ollopaci Any ETA on this one? That would be very useful!

**Comment by skaravad** [comment]
It would be good feature to have, we server most of our apps from a single host/app_name like http://host/<app1> having the base_url as config var makes life easy, thanks in advance.

**Comment by lanceleonard** [comment]
Hi @eexwhyzee!

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
