### ISSUE TITLE
Slow docs site performance

### ISSUE THREAD

**Issue by Dmitry1987** [RedisLabs/redislabs-docs#862]
**Current behavior** (A short description of what you found)
Each page is pretty slow to react (slow to load when browsing links in menu from one to another)
And Chrome also freezes for about 1-2 seconds (like, literally seconds, not ms) when page first renders, it can't scroll. 

**Expected behavior** (A short description of what you expected to find)
Docs are so simple, could work really fast and be very lightweight. I have a feeling I'm navigating some SAP product or another super-heavy web application with trillion buttons or something :) .

**Screenshots** (Paste or drag-and-drop a screenshot)
![image](https://user-images.githubusercontent.com/9369080/84095066-20a2c600-a9b3-11ea-9818-1ffda28da8d5.png)

**Additional context** (Add any other information)
Seems it was over-engineered? :D 
A test shows too many issues for such a simple page

![image](https://user-images.githubusercontent.com/9369080/84095456-3a90d880-a9b4-11ea-93d2-114130c22d79.png)

It's across all docs, not just the page listed above. 
I hope it helps :)

**Comment by bmansheim** [comment]
Hi @Dmitry1987 . You are spot on. We have been looking into this for a while and your analysis certainly gives us more insight.
Just as a test, did you try using incognito?

**Comment by Dmitry1987** [comment]
Interesting, incognito mode actually acts like a usual page, there's still a very brief moment, maybe 0.2-0.5 sec at most, when the page renders (here it seems like literally the DOM rendering just wants is "all" at once to be first drawn, and only then i can scroll it) but it's at least x2-x3 faster than without incognito (this tiny page just literally freeze for 5-6 seconds for real https://docs.redislabs.com/latest/rc/concepts/  while browsing through about 10 links in the sidebar... all other pages are about 2-3 seconds before i can scroll..  yeah i tried a few clicks again, and this page this time took about 4-5 seconds too https://docs.redislabs.com/latest/rc/concepts/data-persistence/)

**Comment by Dmitry1987** [comment]
then i guess docs page verifies user authentication on each click or something like that... maybe cookies or some conditions that react to cookies content etc'.

**Comment by bmansheim** [comment]
@Dmitry1987 Really glad you were able to confirm that. We'll look into it and hopefully make some improvements soon.

**Comment by bmansheim** [comment]
@Dmitry1987 We are working on some small improvements in the site but we noticed that the compression wasn't turned on in the CDN. That seems to have helped. Can you confirm that?

**Comment by Dmitry1987** [comment]
Hi @bmansheim , it seems much better than last time I tried, yup. You can close the ticket if you want as well.

**Comment by bmansheim** [comment]
Thanks for pushing us to do this @Dmitry1987 . The Karma wasn't right until you put in the ticket.
