### ISSUE TITLE
Azure backup syntax

### ISSUE THREAD

**Issue by Dmitry1987** [RedisLabs/redislabs-docs#863]
**Current behavior** (A short description of what you found)
Wrong example of connection string for azure storage

**Additional context** (Add any other information)

The page has wrong number of parts in URL of the azure bucket 

```
abs://:storage_account_access_key@storage_account_name/container_name/[path/]

Where:

storage_account_access_key: the primary access key to the storage account
storage_account_name: the storage account name
url: the URL of the storage account.
container_name: the name of the container, if needed.
path: the backups path, if needed.

```

but there is no "url" so it got me confused :)  a minor bug.

**Comment by Dmitry1987** [comment]
One more question, are you sure the permission "Read bucket permissions" **and "write bucket permissions"** is required?

**Comment by Dmitry1987** [comment]
Can't think of a reason for writing a backup permissions actually.. it only needs to be allowed to PutObject, DeleteObject, and list operations, IMHO. as far as I understand the process.

**Comment by bmansheim** [comment]
Thanks again @Dmitry1987 . I'll get confirmation on that.

**Comment by kaitlynmichael** [comment]
Moving this issue to Jira (DOC-754)
