### ISSUE TITLE
TOC Navigation missing from platform

### ISSUE THREAD

**Issue by alexmilowski** [RedisLabs/redislabs-docs#868]
**Current behavior** (A short description of what you found)

The left navigation seems to have disappeared from the platform docs. It will appear patially if you click on platform ...
<img width="817" alt="Screen Shot 2020-06-10 at 3 02 13 PM" src="https://user-images.githubusercontent.com/1141890/84323458-b06b8000-ab2b-11ea-9ff9-f9ead8052e89.png">

**Expected behavior** (A short description of what you expected to find)

As it was before with it expanded by default ...

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

**Comment by bmansheim** [comment]
Thanks, @alexmilowski , for reporting this. It happens sometimes and goes away when we rerun the build. All better now.
