### ISSUE TITLE
RedisInsight doesn't let me browse all databases

### ISSUE THREAD

**Issue by HitkoDev** [RedisLabs/redislabs-docs#869]
**Current behavior** (A short description of what you found)

`'db' must be an integer between 0 and 15, got '30'`

**Expected behavior** (A short description of what you expected to find)

Since I have `databases 50` in redis config, let me browse database 30.

**Comment by bmansheim** [comment]
Thanks, @HitkoDev .
@slemeur , what are your thoughts?

**Comment by slemeur** [comment]
Hi @HitkoDev, yes I confirm the issue and we will add it to the backlog. 

Out of curiosity (for me :)): how are you using your `50 databases`, why did you choose that approach?

**Comment by HitkoDev** [comment]
I've got a bunch of services which require relatively small cache (a couple thousand items @ ~20kB), so it's more convenient to put them in a single Redis instance with 2GB RAM. They're different enough that I don't want to put them in the same database and use a key prefix, and I don't want to run a separate Redis instance for each service since I want a global eviction policy and, well, managing a single instance is easier than managing 50 of them.

**Comment by Sligcm** [comment]
I also have the same problem, may I ask when the official can fix this BUG?

**Comment by GnaneshKunal** [comment]
Hey @HitkoDev The support was added. Can you try with the latest version of RedisInsight. Thanks!

Here's how it looks like:
![image](https://user-images.githubusercontent.com/20211167/142352140-1b99af6f-99fb-4c14-ae3f-59015d216846.png)

**Comment by HitkoDev** [comment]
@GnaneshKunal just noticed it, works like a charm 👍
