### ISSUE TITLE
RediInsight 1.6 Docker image doesn't work.

### ISSUE THREAD

**Issue by maxisam** [RedisLabs/redislabs-docs#886]
I am using 1.5.0 and it works. When I upgrade to 1.6.0. It doesn't work.

When I roll back the version number, it starts to work again.

Here is the error message.

Traceback (most recent call last):,
  File "./startup.py", line 395, in <module>,
  File "./startup.py", line 378, in create_startup_logger,
  File "/usr/local/lib/python3.6/logging/handlers.py", line 202, in __init__,
    BaseRotatingHandler.__init__(self, filename, 'a', encoding, delay),
  File "/usr/local/lib/python3.6/logging/handlers.py", line 57, in __init__,
    logging.FileHandler.__init__(self, filename, mode, encoding, delay),
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1032, in __init__,
    StreamHandler.__init__(self, self._open()),
  File "/usr/local/lib/python3.6/logging/__init__.py", line 1061, in _open,
    return open(self.baseFilename, self.mode, encoding=self.encoding),
PermissionError: [Errno 13] Permission denied: '/db/redisinsight.log',
Process 8 died: No such process; trying to remove PID file. (/run/avahi-daemon//pid),

**Comment by slemeur** [comment]
Hi @maxisam ! Thanks for reaching out.
Yes, since 1.6, the docker container is rootless which can raise some permission problems.

Can you try doing `docker exec` into your container and running `chown -R 1001 /db`

We are going to add that to the documentation: 
https://github.com/RedisLabs/redislabs-docs/pull/887

**Comment by Sam-Lin-MillersLab** [comment]
but it keeps restarting itself. I can't even SSH into the container.

**Comment by GnaneshKunal** [comment]
@maxisam 

Before starting the container, you have to change the permissions of the db directory if you are using docker volumes.

I guess you are trying to mount a directory as `/db` in redisinsight and redisinsight is run rootless and has the least permissions, so it can't access the mounting directory.

If you have run the command as following:

```
docker run -v myinfo:/db -p 8001:8001 redislabs/redisinsight
```

you have to change the permissions of `myinfo` directory. You can do that by doing `chown -R 1001 myinfo`

**Comment by GnaneshKunal** [comment]
@Sam-Lin-MillersLab 

That is because redisinsight doesn't have permissions to access the directory, and it fails and you must have some container-orchestrator that is simply restarting the container since it failed.

Change the permissions of the db directory and start the process.

**Comment by maxisam** [comment]
Thanks It works by just changing the folder without SSH into the container.
