### ISSUE TITLE
Formatting and missing content on https://docs.redislabs.com/latest/platforms/kubernetes/

### ISSUE THREAD

**Issue by andresrinivasan** [RedisLabs/redislabs-docs#922]
**Current behavior** (A short description of what you found)

Formatting issues and missing content

**Expected behavior** (A short description of what you expected to find)

The reverse of that

**Screenshots** (Paste or drag-and-drop a screenshot)

**Additional context** (Add any other information)

Formatting issues

- https://docs.redislabs.com/latest/platforms/kubernetes/sizing-kubernetes/
- https://docs.redislabs.com/latest/platforms/kubernetes/upgrading-kubernetes-with-operator/
- https://docs.redislabs.com/latest/platforms/kubernetes/kubernetes-logs/

And https://docs.redislabs.com/latest/platforms/kubernetes/kubernetes-cluster-recovery/ ends with a promise of information but leaves you hanging with _The cluster recovery for Kubernetes automates these recovery steps:_

**Comment by bmansheim** [comment]
Hi @andresrinivasan . Thanks for reporting this. The links that you sent look all OK to me. Can you re-check, clear cache, check in incognito, and if it is still a problem send your browser information and we'll get right on it.

**Comment by andresrinivasan** [comment]
My apologies. You're correct I wasn't paying attention and I thought I was sharing page anchors. If you go to https://docs.redislabs.com/latest/platforms/kubernetes/ and scroll down to the sections, you'll see there is code that I believe wants a code block.

In the case of the promised information, search on _The cluster recovery_ and you'll see how it just cuts off.

**Comment by bmansheim** [comment]
OK, @andresrinivasan . Now I see what you mean. You're right about the display of the text. I guess it's not clear enough on those pages that it is displaying summary text from the subpages of the section, with the intention that you would click on the title to see the full text.

That is currently as designed, but we will certainly consider making that more clear.
