### ISSUE TITLE
Feature Request: Authentication for RedisInsight

### ISSUE THREAD

**Issue by benjie91** [RedisLabs/redislabs-docs#968]
**Feature Request**
Currently there is no authentication provided by RedisInsight. Anybody who have access to the web link would be able to see the databases and edit the database settings.

**Comment by dsalaza4** [comment]
Are there any updates on this?

**Comment by banker** [comment]
@K-Jo Ping.

**Comment by johnboy007** [comment]
Hi guys - checking if there has been any update on this?

**Comment by nantiferov** [comment]
I guess as a workaround it's possible to use https://github.com/oauth2-proxy/oauth2-proxy

**Comment by lanceleonard** [comment]
Hi @benjie91, @dsalaza4, & @johnboy007! 

Not sure if you've heard, but RedisInsight has its own repo now: https://github.com/RedisInsight/RedisInsight

As a result, we're closing issues that aren't directly related to the docs published to https://docs.redis.com.

If you still have questions or concerns, please feel free to file a new issue in the new repo.

-- Lance
