### ISSUE TITLE
How to set logging level for RedisInsight

### ISSUE THREAD

**Issue by marcuslange** [RedisLabs/redislabs-docs#987]
**Current behavior** (A short description of what you found)
Insight logs are very noisy.

**Expected behavior** (A short description of what you expected to find)
Ability to set log level with environment variable, or if it is available, documentation on how its set.

**Comment by bmansheim** [comment]
Thanks for that feedback, @marcuslange . I'll pass it to our product managers and see what they can do.

**Comment by slemeur** [comment]
Hi @marcuslange : We added the ability to configure the log level with environment variables: https://docs.redislabs.com/latest/ri/installing/configurations/#riloglevel

Right now the default is Warning - so it'll be much less noisy.

Thanks for reaching out and creating the ticket!
